config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: %i[index show new create] do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: (0..5).to_a }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new restaurant_params
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new review_params
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def find_restaurant
    @restaurant = Restaurant.find params[:restaurant_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <!-- As a link -->
  <nav class="navbar navbar-light bg-light">
    <%= link_to "Restaurants App", restaurants_path, class: "link-success" %>
    <%= link_to "Add Restaurant", new_restaurant_path, class: "btn btn-outline-primary"%>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<ul>
  <% @restaurants.each do |rest| %>
    <li><%= rest.name %><span><%= link_to "See details", restaurant_path(rest), class: "link-primary"%></span></li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= simple_form_for @restaurant do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :category %>
<%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h2><%= @restaurant.address %></h2>
<h5><%= @restaurant.category %></h5>
<ul>
<% @restaurant.reviews.each do |review| %>
  <li><%= review.content %> - <%= review.rating %></li>
<% end %>
</ul>

<%= link_to "Add review", new_restaurant_review_path(@restaurant), class: "link-primary"%>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.submit %>
<% end %>